### ISSUE TITLE
setup.py problems

### ISSUE THREAD

**Issue by hjw8256** [strongswan/strongMan#140]
I try to install strongMan but have some problems. please help:) Thanks

livechina@livechina:~$ cd strongMan
livechina@livechina:~/strongMan$ sudo ./setup.py install
Start strongMan installation
        - Virtualenv
        - Requirements
        - Database migration
                Delete strongMan/db.sqlite3
[Errno 2] No such file or directory: '/home/livechina/strongMan/strongMan/db.sqlite3'
Traceback (most recent call last):
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/oscrypto/_openssl/_libcrypto_ctypes.py", line 304, in <module>
    libcrypto.EVP_PKEY_size.argtypes = [
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libcrypto.so.3: undefined symbol: EVP_PKEY_size. Did you mean: 'EVP_PKEY_free'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/livechina/strongMan/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/livechina/strongMan/strongMan/apps/connections/models/__init__.py", line 1, in <module>
    from .connections import *
  File "/home/livechina/strongMan/strongMan/apps/connections/models/connections.py", line 10, in <module>
    from strongMan.apps.connections.models.common import State
  File "/home/livechina/strongMan/strongMan/apps/connections/models/common.py", line 3, in <module>
    from strongMan.apps.certificates.models import MessageObj
  File "/home/livechina/strongMan/strongMan/apps/certificates/models/__init__.py", line 1, in <module>
    from .certificates import *
  File "/home/livechina/strongMan/strongMan/apps/certificates/models/certificates.py", line 8, in <module>
    from ..container_reader import X509Reader
  File "/home/livechina/strongMan/strongMan/apps/certificates/container_reader.py", line 7, in <module>
    from oscrypto import keys as k
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/oscrypto/_openssl/_libcrypto.py", line 15, in <module>
    from ._libcrypto_ctypes import (
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/oscrypto/_openssl/_libcrypto_ctypes.py", line 688, in <module>
    raise FFIEngineError('Error initializing ctypes')
oscrypto._ffi.FFIEngineError: Error initializing ctypes
Command '['/home/livechina/strongMan/env/bin/python', '/home/livechina/strongMan/manage.py', 'makemigrations', 'certificates', '--settings=strongMan.settings.local']' returned non-zero exit status 1.

**Comment by tobiasbrunner** [comment]
> AttributeError: /lib/x86_64-linux-gnu/libcrypto.so.3: undefined symbol: EVP_PKEY_size. Did you mean: 'EVP_PKEY_free'?

OpenSSL 3 replaced that with `EVP_PKEY_get_size` and only provides a define for `EVP_PKEY_size`. So that probably doesn't work with that function wrapping oscrpyto does. I guess you have to increase the version for that packet, try updating `requirements.txt` with `oscrypto==1.3.0`.

**Comment by hjw8256** [comment]
I updated requirements.txt  with
Django==4.2.3
oscrypto==1.3.0
asn1crypto==1.5.1
pyaes==1.6.1
django-tables2==2.6.0
vici==5.9.11
gunicorn==20.1.0
dj_static==0.0.6
but still have some errors. Thanks:)

livechina@livechina:~/strongMan$ sudo ./setup.py install
Start strongMan installation
        - Virtualenv
        - Requirements
        - Database migration
                Delete strongMan/db.sqlite3
[Errno 2] No such file or directory: '/home/livechina/strongMan/strongMan/db.sqlite3'
Traceback (most recent call last):
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/apps/config.py", line 210, in create
    app_module = import_module(app_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'server_connections'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/livechina/strongMan/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/livechina/strongMan/env/lib/python3.10/site-packages/django/apps/config.py", line 212, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'server_connections'. Check that 'strongMan.apps.server_connections.apps.serverConnectionsConfig.name' is correct.
Command '['/home/livechina/strongMan/env/bin/python', '/home/livechina/strongMan/manage.py', 'makemigrations', 'certificates', '--settings=strongMan.settings.local']' returned non-zero exit status 1.

**Comment by hjw8256** [comment]
i solved after updating requirements.txt with oscrypto==1.3.0,asn1crypto==1.5.1. thank .you:)
